### ISSUE TITLE
Decide on how to display the content

### ISSUE THREAD

**Issue by mcelearr** [wales-coop/wales-coop#13]
There are several ideas for this:
- A wheel divided into sections that when clicked on pop out with the content related to that section.
- A clockface that represents a year (with months instead of hours) which has important business dates marked out on it.
- A linear graph that shows a year and spikes in activity from google searches for certain search terms that are related to content.

We need to draw up wireframes for how we decide to display this information and share it with the client as soon as possible.

**Comment by helau64** [comment]
Doughnut chart that fills as user answers [survey questions ](http://tympanus.net/codrops/2014/04/01/minimal-form-interface/)?

**Comment by mcelearr** [comment]
Yep and using http://www.chartjs.org/
