### ISSUE TITLE
Develop list of questions and content sections

### ISSUE THREAD

**Issue by mcelearr** [wales-coop/wales-coop#17]
# Overview

Think about how we want to bespoke the user experience in a way which provides the most value. The current idea is to have the sections of the chart be different sizes based on the answers to the questions, with each of the sections representing a different topic. The sections will have the links to information coming out of them. Think about the kind of ways we can chop up the business advice that is available.
# Some Principles
- The fewer questions the better!
- Nice short questions with simple answers.
- What data is useful for Wales Co-op to harvest? Don't lose sight of the fact that one of the real goals here is to convert these users into Wales Co-op or SBW customers.
# How it will look

This is how we imagine it looking:

[Desktop version](https://wireframe.cc/w5GnCt)

[Mobile Version page 1](https://wireframe.cc/1N4L35)

[Mobile Version page 2](https://wireframe.cc/gmKU8t)

**Comment by flaherty1984** [comment]
Hi Guys,

What do you think of these questions? I have sorted them into sections that relate to the social business Wales website.

Before you start a Social Business
1. Have you started your Social Enterprise?

Starting a Social Enterprise
1. Do you have an engaged group of people
2. Have you formed a legal structure
3. Are you bidding for contracts or seeking funding
4. Are you employing staff

Running a Social Business
1. Are you confident in your organisations governance?
2. Do you use a form of Social Accounting
3. Do you have a skilled management

Growing A Social Business
1. Do you have a sustainability plan
2. Are you looking to grow (expand, diversify etc)
3. Are you thinking of grouping together with other like minded groups?
4. Do you think your idea could work in other areas?
5. Would you like to buy another business to help you grow?

**Comment by mcelearr** [comment]
Hi @flaherty1984 this is excellent - exactly what we were looking for. I have divided the content into the questions that I think match them.
