### ISSUE TITLE
Website not displaying correctly on iphone and on Internet Explorer 11.

### ISSUE THREAD

**Issue by flaherty1984** [wales-coop/wales-coop#74]
Morning Guy's,

The website seems to be working on iPad but not on the iPhone the information from each section of the doughnut does not display.

On internet explorer 11 the website is unusable, it looks like the logo's are too big and overlaying the questions and information,

Thanks 

Marc

**Comment by mcelearr** [comment]
Hi @flaherty1984, to get the app used by as many people as possible, we should make it compatible with IE and safari. At the moment, it has been developed almost entirely for chrome, just to get something to you in the four days. We will make it cross-browser compatible in the next sprint.

**Comment by flaherty1984** [comment]
Ok thanks Rory,

I will continue to test on Chrome and iPad,

**Comment by g-sam** [comment]
This issue will be partially addressed in the second sprint, but browser-compatibility is not part ofnthe core scope.
